# Generated by Django 4.2.25 on 2025-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_auto_20251031_1449"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={},
        ),
        migrations.AddField(
            model_name="entry",
            name="sentiment",
            field=models.CharField(default="neutral", max_length=20),
        ),
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
